# Generated by Django 4.2.7 on 2025-12-21 10:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('user_id', models.CharField(editable=False, help_text='Auto-generated unique user ID (format: u-XXXXXX)', max_length=20, unique=True)),
                ('email', models.EmailField(help_text='Email address (used for login)', max_length=254, unique=True)),
                ('phone', models.CharField(help_text='Phone number (must be unique)', max_length=20, unique=True)),
                ('location', models.CharField(help_text='User location/address', max_length=255)),
                ('blood_group', models.CharField(blank=True, choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('O+', 'O+'), ('O-', 'O-'), ('AB+', 'AB+'), ('AB-', 'AB-')], help_text='Blood group', max_length=10)),
                ('gender', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], help_text='Gender', max_length=10)),
                ('age', models.IntegerField(blank=True, help_text='Age in years', null=True)),
                ('role', models.CharField(choices=[('PATIENT', 'Patient'), ('DOCTOR', 'Doctor'), ('ADMIN', 'Admin')], default='PATIENT', help_text='User role (determines permissions)', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='Full name', max_length=100)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'db_table': 'users',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DoctorInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_number', models.CharField(help_text='Medical license number (must be unique)', max_length=50, unique=True)),
                ('qualification', models.TextField(help_text='Medical qualifications (e.g., MBBS, MD)')),
                ('education', models.TextField(blank=True, help_text='Educational background and institutions')),
                ('specialization', models.CharField(help_text='Medical specialization (e.g., Cardiology, Dermatology)', max_length=100)),
                ('practice_location', models.CharField(help_text='Current practice location/hospital', max_length=255)),
                ('experience_years', models.IntegerField(blank=True, help_text='Years of medical practice experience', null=True)),
                ('bio', models.TextField(blank=True, help_text='Professional biography', max_length=1000)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', help_text='Application status (pending admin approval)', max_length=20)),
                ('is_verified', models.BooleanField(default=False, help_text='Verified by admin')),
                ('rating_avg', models.DecimalField(decimal_places=2, default=0.0, help_text='Average rating (0.00 to 5.00)', max_digits=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(help_text='User account associated with this doctor profile', on_delete=django.db.models.deletion.CASCADE, related_name='doctor_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Doctor Information',
                'verbose_name_plural': 'Doctor Information',
                'db_table': 'doctor_information',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user'], name='doctor_info_user_id_1bd2e3_idx'), models.Index(fields=['status'], name='doctor_info_status_411c7b_idx'), models.Index(fields=['specialization'], name='doctor_info_special_e7d2c5_idx'), models.Index(fields=['is_verified'], name='doctor_info_is_veri_39abc9_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['email'], name='users_email_4b85f2_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['user_id'], name='users_user_id_83dd09_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['role'], name='users_role_0ace22_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['phone'], name='users_phone_af6883_idx'),
        ),
    ]
