# Generated by Django 4.2.7 on 2025-12-22 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorinformation',
            name='availability_status',
            field=models.CharField(choices=[('available', 'Available'), ('busy', 'Busy'), ('unavailable', 'Unavailable')], default='unavailable', help_text='Current availability status for appointments', max_length=20),
        ),
        migrations.AddField(
            model_name='doctorinformation',
            name='city',
            field=models.CharField(blank=True, help_text='City of practice', max_length=100),
        ),
        migrations.AddField(
            model_name='doctorinformation',
            name='clinic_address',
            field=models.TextField(blank=True, help_text='Clinic or practice address'),
        ),
        migrations.AddField(
            model_name='doctorinformation',
            name='consultation_fee',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Consultation fee in local currency', max_digits=10),
        ),
        migrations.AddField(
            model_name='doctorinformation',
            name='email',
            field=models.EmailField(blank=True, help_text='Professional email address', max_length=254),
        ),
        migrations.AddField(
            model_name='doctorinformation',
            name='languages',
            field=models.CharField(default='English', help_text='Languages spoken (comma-separated)', max_length=255),
        ),
        migrations.AddField(
            model_name='doctorinformation',
            name='phone',
            field=models.CharField(blank=True, help_text='Contact phone number', max_length=20),
        ),
        migrations.AddField(
            model_name='doctorinformation',
            name='pincode',
            field=models.CharField(blank=True, help_text='Postal/ZIP code', max_length=10),
        ),
        migrations.AddField(
            model_name='doctorinformation',
            name='profile_image',
            field=models.ImageField(blank=True, help_text='Doctor profile picture', null=True, upload_to='doctors/profiles/'),
        ),
        migrations.AddField(
            model_name='doctorinformation',
            name='rating_count',
            field=models.IntegerField(default=0, help_text='Total number of ratings'),
        ),
        migrations.AddField(
            model_name='doctorinformation',
            name='state',
            field=models.CharField(blank=True, help_text='State/province of practice', max_length=100),
        ),
        migrations.AddIndex(
            model_name='doctorinformation',
            index=models.Index(fields=['availability_status'], name='doctor_info_availab_a40390_idx'),
        ),
        migrations.AddIndex(
            model_name='doctorinformation',
            index=models.Index(fields=['city'], name='doctor_info_city_f0c5bb_idx'),
        ),
        migrations.AddIndex(
            model_name='doctorinformation',
            index=models.Index(fields=['rating_avg'], name='doctor_info_rating__eb70c0_idx'),
        ),
    ]
