# Generated by Django 4.2.7 on 2025-12-25 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_doctorinformation_availability_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorinformation',
            name='diseases_treated',
            field=models.JSONField(blank=True, default=list, help_text='List of diseases/conditions the doctor treats'),
        ),
    ]
