# Generated by Django 4.2.7 on 2026-01-03 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_doctorinformation_diseases_treated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorinformation',
            name='diseases_treated',
            field=models.TextField(blank=True, default='', help_text='Diseases treated by the doctor (comma-separated)'),
        ),
    ]
