# Generated by Django 4.2.7 on 2025-12-24 09:58

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0002_doctorinformation_availability_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment_number', models.CharField(help_text='Unique appointment number (e.g., APT-20231224-001)', max_length=20, unique=True)),
                ('appointment_date', models.DateField(help_text='Date of the appointment')),
                ('appointment_time', models.TimeField(blank=True, help_text='Time of the appointment', null=True)),
                ('serial_number', models.IntegerField(help_text='Serial number for the day (queue position)', validators=[django.core.validators.MinValueValidator(1)])),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('CONFIRMED', 'Confirmed'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('NO_SHOW', 'No Show')], default='CONFIRMED', help_text='Appointment status', max_length=20)),
                ('patient_notes', models.TextField(blank=True, help_text='Patient notes or reason for visit')),
                ('doctor_notes', models.TextField(blank=True, help_text='Doctor notes after consultation')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('doctor', models.ForeignKey(help_text='Doctor for this appointment', on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='users.doctorinformation')),
                ('patient', models.ForeignKey(help_text='Patient who booked the appointment', on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Appointment',
                'verbose_name_plural': 'Appointments',
                'db_table': 'appointments',
                'ordering': ['appointment_date', 'serial_number'],
                'indexes': [models.Index(fields=['doctor', 'appointment_date'], name='appointment_doctor__4449b5_idx'), models.Index(fields=['patient', 'appointment_date'], name='appointment_patient_ee8848_idx'), models.Index(fields=['appointment_number'], name='appointment_appoint_e7d91b_idx'), models.Index(fields=['status'], name='appointment_status_9fecd6_idx')],
                'unique_together': {('doctor', 'appointment_date', 'serial_number')},
            },
        ),
    ]
