# Generated by Django 4.2.7 on 2025-12-22 04:32

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0002_doctorinformation_availability_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('review_text', models.TextField(blank=True, max_length=200, validators=[django.core.validators.MinLengthValidator(0)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='users.doctorinformation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_ratings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Doctor Rating',
                'verbose_name_plural': 'Doctor Ratings',
                'db_table': 'doctor_ratings',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['doctor', '-created_at'], name='doctor_rati_doctor__088ed2_idx'), models.Index(fields=['rating'], name='doctor_rati_rating_341862_idx')],
                'unique_together': {('doctor', 'user')},
            },
        ),
    ]
