# Generated by Django 4.2.7 on 2025-12-24 09:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_doctorinformation_availability_status_and_more'),
        ('doctors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.IntegerField(choices=[(0, 'Sunday'), (1, 'Monday'), (2, 'Tuesday'), (3, 'Wednesday'), (4, 'Thursday'), (5, 'Friday'), (6, 'Saturday')], help_text='Day of the week (0=Sunday, 6=Saturday)')),
                ('start_time', models.TimeField(help_text='Schedule start time (e.g., 09:00)')),
                ('end_time', models.TimeField(help_text='Schedule end time (e.g., 16:00)')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this schedule is currently active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='users.doctorinformation')),
            ],
            options={
                'verbose_name': 'Doctor Schedule',
                'verbose_name_plural': 'Doctor Schedules',
                'db_table': 'doctor_schedules',
                'ordering': ['day_of_week', 'start_time'],
                'indexes': [models.Index(fields=['doctor', 'day_of_week'], name='doctor_sche_doctor__1c8667_idx'), models.Index(fields=['is_active'], name='doctor_sche_is_acti_98a2b3_idx')],
                'unique_together': {('doctor', 'day_of_week')},
            },
        ),
    ]
