# Generated by Django 4.2.7 on 2025-12-24 17:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appointment', '0005_alter_appointment_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0002_doctorinformation_availability_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chief_complaint', models.TextField(help_text='Main reason for visit')),
                ('diagnosis', models.TextField(help_text='Medical diagnosis')),
                ('temperature', models.DecimalField(blank=True, decimal_places=1, help_text='Temperature in Fahrenheit', max_digits=4, null=True)),
                ('blood_pressure_systolic', models.IntegerField(blank=True, null=True)),
                ('blood_pressure_diastolic', models.IntegerField(blank=True, null=True)),
                ('heart_rate', models.IntegerField(blank=True, help_text='Beats per minute', null=True)),
                ('respiratory_rate', models.IntegerField(blank=True, null=True)),
                ('medications', models.TextField(help_text='Prescribed medications')),
                ('dosage', models.CharField(help_text='Dosage and frequency', max_length=255)),
                ('instructions', models.TextField(blank=True, help_text='Special instructions for patient')),
                ('doctor_notes', models.TextField(blank=True, help_text='Additional notes by doctor')),
                ('follow_up_required', models.BooleanField(default=False)),
                ('follow_up_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to='appointment.appointment')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to='users.doctorinformation')),
                ('patient', models.ForeignKey(limit_choices_to={'role': 'PATIENT'}, on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['doctor', 'created_at'], name='prescriptio_doctor__87d891_idx'), models.Index(fields=['patient', 'created_at'], name='prescriptio_patient_9a133f_idx'), models.Index(fields=['appointment'], name='prescriptio_appoint_2c10b0_idx')],
            },
        ),
    ]
